server:
  port: 8082

spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
